### ISSUE TITLE
Failed to parse configuration error.

### ISSUE THREAD

**Issue by man4ish** [JCVenterInstitute/OMeta-Public#4]
![error](https://user-images.githubusercontent.com/6385968/63134272-b853a580-bf96-11e9-8b5b-87be5a5d3ef1.png)
I am using following configuration. (I am using password instead of welcome as i used the same while creating mysql database).

[GUID_SERVER_URL] = jdbc:mysql://localhost:3306/ifx_projects
[GUID_SERVER_USERNAME] = ifx_projects_adm
[GUID_SERVER_PASSWORD] = password

[OMETA_SERVER_URL] = jdbc:mysql://localhost:3306/jcvi_guid
[OMETA_SERVER_USERNAME] = guid_admin
[OMETA_SERVER_PASSWORD] = password

I am new to open ldap and created following ldap
foo.example.org
so i use
LDAP_URL=ldap//foo.example.org:389/ but what should i write for company domain?
if i replace [COMPANY_DOMAIN] with example and run it

./wildfly-10.0.0.Final/bin/standalone.sh -Djboss.server.base.dir=wildfly-10.0.0.Final/standalone-ometa

i get WFLYCTL0085: Failed to parse configuration error.

I am not sure how to fix above issue.

Regards

**Comment by singhindresh** [comment]
Hi Manish, Please contact your LDAP administrator for correct URL. If you want to install the local LDAP then please download openLDAP (https://www.openldap.org/software/download/) and install it.  LDAP URL will depend on the DNS name of the server where the LDAP is installed. If you prefer, we can setup a meeting to help you with installation and provide quick overview.

Regards
 Indresh

**Comment by man4ish** [comment]
Thanks for prompt reply. Can we setup a meeting tomorrow or earliest.

**Comment by singhindresh** [comment]
Manish, If you don't have LDAP or if you don't want to setup LDAP then you can setup Property file Based Identity Store (http://docs.wildfly.org/15/WildFly_Elytron_Security.html#Properties_File_Based_Authentication_Migration) or MySQL database identity store (http://docs.wildfly.org/15/WildFly_Elytron_Security.html#Database_Authentication_Migration). 

Thanks,
Indresh

**Comment by singhindresh** [comment]
Lead developer is vacation and I need few days to schedule the meeting. Probably next week.

Thanks
 Indresh

**Comment by man4ish** [comment]
For  Property file Based Identity Store, may i know where do i need to make changes (in standalone.xml only). I am just asking as i am new to Jboss world.

<security-domains>
  <security-domain name="application-security">
    <authentication>
      <login-module code="UsersRoles" flag="required">
        <module-option name="usersProperties" value="file://${jboss.server.config.dir}/example-users.properties"/>
        <module-option name="rolesProperties" value="file://${jboss.server.config.dir}/example-roles.properties"/>
      </login-module>
    </authentication>
  </security-domain>
..........................
</security-domains>

**Comment by man4ish** [comment]
Can you pls schedule meeting today for setting up LDAP locally as i need to use ometap urgently. 


Thanks

**Comment by singhindresh** [comment]
Hi Manish,
  What is your email? So that I can schedule the meeting for installation and configuration.
Thanks
 Indresh

**Comment by man4ish** [comment]
mandecent.gupta@gmail.com

**Comment by man4ish** [comment]
Can you pls update me about login error was discussed last time. I need it urgently so pls update me.

Thanks & Regards
