### ISSUE TITLE
Trying to use MySQL 8

### ISSUE THREAD

**Issue by adamw-lilly** [JCVenterInstitute/OMeta-Public#5]
I've been trying to get OMeta to work with MySQL 8 and have run into several problems. I have overcome a few, but am now up against a driver problem that I think is more than I want to solve. It has to do with changes from MySQL 5.x to MySQL 8.x specifically:

`Caused by: java.sql.SQLException: Unknown system variable 'tx_isolation'`

This happens when trying to start up Wildfly with OMeta.

Bottom line: does anyone have OMeta working with MySQL 8?

**Comment by kscgl** [comment]
You need to replace mysql-java-connector with version 8 in Wildfly to be able to use MySQL 8. You can follow the steps below;

1) Download mysql java connector for 8 (https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.19.tar.gz - latest one as of now)
2) Remove mysql-connector-java-5.1.14-bin.jar from ..wildfly/modules/system/layers/base/com/mysql/main/ and copy mysql-connector-java-8.0.19.jar to there.
3) com.mysql.jdbc.Driver is deprecated in v8 so you need to replace it with com.mysql.cj.jdbc.Driver in standalone.xml
4) Change resource-root path to mysql-connector-java-8.0.19.jar in ..wildfly/modules/system/layers/base/com/mysql/main/module.xml

Wildfly should start without any problem after this.

We haven't tested OMeta with MySQL 8 so you may face other issues. We recommend to install and use MySQL 5 until we fully test the application with MySQL 8. 

We can setup a meeting to help you with MySQL 5 & OMeta installation and provide quick overview if you prefer so.

Thanks,
Mehmet

**Comment by adamw-lilly** [comment]
Thanks! I have downgraded to MySQL 5.7 and that seems to operate fine so far. But I have another problem if you could help. I believe OMeta requires (?) LDAP. I do not have an LDAP server (this is a clean install on a single system). Can you instruct me on how to _not_ use LDAP in OMeta?

**Comment by kscgl** [comment]
Great! 

You can use Wildfly's file based authentication instead of LDAP. (https://docs.wildfly.org/15/WildFly_Elytron_Security.html#Properties_File_Based_Authentication_Migration)

- Replace LDAP login module (org.jboss.security.auth.spi.LdapExtLoginModule) with UsersRoles login module in standalone.xml

```
<login-module code="UsersRoles" flag="required">
  <module-option name="usersProperties" value="${jboss.server.config.dir}/application-users.properties"/>
  <module-option name="rolesProperties" value="${jboss.server.config.dir}/application-roles.properties"/>
  <module-option name="password-stacking" value="useFirstPass"/>
</login-module>
```

Your security domain should look like this;

```
<authentication>
  <login-module code="Remoting" flag="optional">
    <module-option name="password-stacking" value="useFirstPass"/>
  </login-module>
  <login-module code="UsersRoles" flag="required">
    ...
  </login-module>
  <login-module code="org.jboss.security.auth.spi.DatabaseServerLoginModule" flag="sufficient">
    ..
  </login-module>
</authentication>
```
Then you need to add an application user to Wildfly. (https://docs.wildfly.org/15/WildFly_Elytron_Security.html#add-a-user) 

I prefer to use add-user utility (../wildfly/bin/add-user.sh or ../wildfly/bin/add-user.bat). username(s) should match with the ones in OMeta Actor table. 

Thanks,
Mehmet

**Comment by adamw-lilly** [comment]
I performed your changes above and restarted Wildfly.

I still cannot login. I have the login screen from OMeta. I know there is a single user in the actor table called 'testuser'. But no matter what I type or what password I use, I cannot log in. I'm stuck! I'm not getting any error messages anywhere that I can detect so I'm unsure why it is failing and have nothing to follow.

Any suggestions? Any logs I can look at that might tell me more?

**Comment by adamw-lilly** [comment]
I should add that I did run add-user.sh to create the user 'testuser' for Wildfly. I do see that value in the applciation-roles.properties file which gives me some confidence it did create that user.

**Comment by kscgl** [comment]
You need to configure logging as below to see more details since it's being authenticated within Wildfly server. 

1. Change level name to DEBUG under logging subsystem in standalone.xml. 
  
```
<subsystem xmlns="urn:jboss:domain:logging:6.0">
  <console-handler name="CONSOLE">
    <level name="INFO"/> -->  <level name="DEBUG"/>
    <formatter>
      <named-formatter name="COLOR-PATTERN"/>
    </formatter>
  </console-handler>
....
```

2. Add jboss security to logging subsystem. 

```
<logger category="org.jboss.security">
  <level name="DEBUG"/>
</logger>
```

You should be able to see the error after applying these changes and restarting the server.

Eg; I am getting the error below when I attempt to login with wrong password.

```
11:24:49,362 DEBUG [org.jboss.security] (default task-1) PBOX00283: Bad password for username testuser
11:24:49,362 DEBUG [org.jboss.security] (default task-1) PBOX00206: Login failure: javax.security.auth.login.FailedLoginException: PBOX00070: Password invalid/Password required
```

**Comment by adamw-lilly** [comment]
Very helpful! I'm now getting error messages and will continue my debugging! Thanks!

**Comment by adamw-lilly** [comment]
Alright. Here are my issues reported now. I'm unclear what to do about 'MalformedURLException'. I'm not sure where it is asking for defaultUsers.properties (it is not in the standalone.xml at all?). But the other file (application-users.properties) is in fact there.....
...
20:16:37,448 DEBUG [org.jboss.security] (default task-1) PBOX00287: Failed to open properties file from URL: java.net.MalformedURLException: no protocol: defaultUsers.properties
...
20:16:37,450 DEBUG [org.jboss.security] (default task-1) PBOX00287: Failed to open properties file from URL: java.net.MalformedURLException: no protocol: /opt/wildfly-16.0.0.Final/standalone-ometa/configuration/application-users.properties
...
20:16:37,452 DEBUG [org.jboss.security] (default task-1) PBOX00287: Failed to open properties file from URL: java.net.MalformedURLException: no protocol: defaultRoles.properties
...
20:16:37,453 DEBUG [org.jboss.security] (default task-1) PBOX00287: Failed to open properties file from URL: java.net.MalformedURLException: no protocol: /opt/wildfly-16.0.0.Final/standalone-ometa/configuration/application-roles.properties
...
20:16:37,461 DEBUG [org.jboss.security] (default task-1) PBOX00283: Bad password for username testuser
20:16:37,485 DEBUG [org.jboss.security] (default task-1) PBOX00283: Bad password for username testuser
20:16:37,486 DEBUG [org.jboss.security] (default task-1) PBOX00206: Login failure: javax.security.auth.login.FailedLoginException: PBOX00070: Password invalid/Password required
...

**Comment by adamw-lilly** [comment]
If I add 'file://' to application-roles.properties in the standalone.xml, it seems to get past those. But still, there is no 'defaultUsers.properties' that I know of? Unsure there that is declared or why it would be trying to use a URL protocol?

**Comment by adamw-lilly** [comment]
i.e. here is what I did for application-users and roles in standalone.xml....

<login-module code="UsersRoles" flag="required">
<module-option name="usersProperties" value="file://${jboss.server.config.dir}/application-users.properties"/>
<module-option name="rolesProperties" value="file://${jboss.server.config.dir}/application-roles.properties"/>
<module-option name="password-stacking" value="useFirstPass"/>
</login-module>

But I cannot do the same with defaultUsers.properties because it is not declare in standalone.xml....

**Comment by kscgl** [comment]
I've tried file based login on Windows machine. Apparently, 'file://' has to be added in some cases (https://docs.jboss.org/author/display/WFLY/Properties+File+Based+Authentication+Migration) 

You can ignore exceptions related to defaultUsers/defaultRoles or you can add the lines below; 
(https://developer.jboss.org/wiki/UsersRolesLoginModule)

```
<module-option name="defaultUsersProperties" value="file://${jboss.server.config.dir}/application-users.properties"/>
<module-option name="defaultRolesProperties" value="file://${jboss.server.config.dir}/application-roles.properties"/>
```

You should be able to login with correct credentials though if there is no exception for application-*.properties

**Comment by adamw-lilly** [comment]
Alright. That did take care of the trouble loading the defaultUser.properties. But I still can't log in. It says 

21:17:38,639 DEBUG [org.jboss.security] (default task-1) PBOX00283: Bad password for username testuser
21:17:38,664 DEBUG [org.jboss.security] (default task-1) PBOX00283: Bad password for username testuser
21:17:38,666 DEBUG [org.jboss.security] (default task-1) PBOX00206: Login failure: javax.security.auth.login.FailedLoginException: PBOX00070: Password invalid/Password required

However, I'm quite sure the password is correct. As a test, I tried an invalid user and got the same error....

21:18:50,394 DEBUG [org.jboss.security] (default task-1) PBOX00283: Bad password for username foobar
21:18:50,397 DEBUG [org.jboss.security] (default task-1) PBOX00206: Login failure: javax.security.auth.login.FailedLoginException: PBOX00070: Password invalid/Password required

I'm suspecting it is still not recognizing any users in Wildfly. Any way I can check that?

**Comment by adamw-lilly** [comment]
Ah! Interesting. The password in the application-users.properties file was a hash or otherwise encrypted. When I made it plain text, it seemed to work.

**Comment by adamw-lilly** [comment]
I think you can close this ticket now as I can get into the system. There are other issues appearing now (in the Wildfly console), but let me prowl around a little and see if I can articulate what is happening. Thanks!

**Comment by kscgl** [comment]
Perfect! 

For future reference, you can use add-user script to replace password. Or you can remove that line from properties file and add the user again if you forget the password. 

Please be aware that we've committed some bug fixes past couple weeks for initial SQL. And again we can setup a meeting to provide a quick overview if you prefer so.
