### ISSUE TITLE
Unable to Create a New Project

### ISSUE THREAD

**Issue by adamw-lilly** [JCVenterInstitute/OMeta-Public#6]
Although I can access my installed site now, I am unable to create a project. The web site replies with this:

`org.jcvi.ometa.exception.DetailedException: Exception during getGUIDBlockjava.io.IOException: Server returned HTTP response code: 500 for URL: http://ip-172-31-10-170.us-east-2.compute.internal:8080/guid/GuidClientServer?Request=GET&Size=1&Namespace=GUID_SERVLET`

Here's what I see in the log...

```
...
2020-02-13 16:30:44,355 ERROR [org.jtc.app_db_interface.guid.web.GuidServlet] (default task-13) Exception handling Guid Request: org.jtc.common.ejb.api.exception.SystemErrorException: org.jtc.common.ejb.api.exception.SystemErrorException
...
Caused by: org.jboss.ejb.client.RequestSendFailedException: EJBCLIENT000409: No more destinations are available
...
```

I think it could be caused by standalone.xml configuration? Perhaps around the jcvi (GUID SERVER) set up. But no matter what mysql user I identify there (and I'm assured that the one I'm using *can* see the jcvi database), it doesn't work. Other thoughts?

**Comment by kscgl** [comment]
I believe it's related to GUID, not OMeta application itself. It doesn't seem to like 'localhost'. Can you follow the steps below to generate your own GUID instance;

Replace YOUR_IP_ADDRESS with ip-172-31-10-170.us-east-2.compute.internal and $WILDFLY_DIR with your Wildfly directory

```
git clone https://github.com/JCVenterInstitute/GUID.git 
cd GUID 
sed -i "s~localhost~YOUR_IP_ADDRESS~g" resources/src/main/resources/GuidDBInterface.properties 
mvn package -DskipTests 
cp -R ear/target/GuidDBInterface.ear $WILDFLY_DIR/standalone-ometa/deployments/
```
